In [1]:
import yaml
import pandas as pd
def extract_deliveries(file_path):
    with open(file_path, 'r') as f:
        data = yaml.safe_load(f)

    innings = data['innings']
    rows = []

    for inning in innings:
        for inning_name, inning_data in inning.items():
            team = inning_data['team']
            for delivery in inning_data['deliveries']:
                for ball_number, ball_info in delivery.items():
                    row = {
                        'inning': inning_name,
                        'batting_team': team,
                        'ball': ball_number,
                        'batsman': ball_info.get('batsman'),
                        'bowler': ball_info.get('bowler'),
                        'runs': ball_info['runs']['total'],
                        'extras': ball_info.get('extras', {}),
                        'wicket': ball_info.get('wicket', {})
                    }
                    rows.append(row)
    return pd.DataFrame(rows)

df = extract_deliveries("/Users/aalapdesai/cricket-analytics/data/external/t20s_male/1439893.yaml")
df.to_csv("/Users/aalapdesai/cricket-analytics/data/raw/t20_sample_clean.csv", index=False)

In [2]:
df.head(10)

,inning,batting_team,ball,batsman,bowler,runs,extras,wicket
0,1st innings,Bangladesh,0.1,Parvez Hossain Emon,Arshdeep Singh,0,{},{}
1,1st innings,Bangladesh,0.2,Parvez Hossain Emon,Arshdeep Singh,0,{},{}
2,1st innings,Bangladesh,0.3,Parvez Hossain Emon,Arshdeep Singh,1,{},{}
3,1st innings,Bangladesh,0.4,Liton Das,Arshdeep Singh,4,{},{}
4,1st innings,Bangladesh,0.5,Liton Das,Arshdeep Singh,0,{},"{'player_out': 'Liton Das', 'fielders': ['RK S..."
5,1st innings,Bangladesh,0.6,Nazmul Hossain Shanto,Arshdeep Singh,1,{},{}
6,1st innings,Bangladesh,1.1,Nazmul Hossain Shanto,HH Pandya,1,{},{}
7,1st innings,Bangladesh,1.2,Parvez Hossain Emon,HH Pandya,6,{},{}
8,1st innings,Bangladesh,1.3,Parvez Hossain Emon,HH Pandya,0,{},{}
9,1st innings,Bangladesh,1.4,Parvez Hossain Emon,HH Pandya,0,{},{}

In [3]:
df.describe()

             ball        runs
count  193.000000  193.000000
mean     8.301036    1.341969
std      5.360533    1.700842
min      0.100000    0.000000
25%      3.700000    0.000000
50%      7.600000    1.000000
75%     11.600000    1.000000
max     19.500000    6.000000

In [4]:
df.dtypes

inning           object
batting_team     object
ball            float64
batsman          object
bowler           object
runs              int64
extras           object
wicket           object
dtype: object

In [1]:
import pandas as pd
import ast

In [4]:
import pandas as pd
# Example file
file_path = '/Users/aalapdesai/cricket-analytics/data/raw/20240629_India_vs_South_Africa.csv'
df = pd.read_csv(file_path)
df

,inning,batting_team,ball,batsman,bowler,runs,extras,wicket
0,1st innings,India,0.1,RG Sharma,M Jansen,1,{},{}
1,1st innings,India,0.2,V Kohli,M Jansen,4,{},{}
2,1st innings,India,0.3,V Kohli,M Jansen,4,{},{}
3,1st innings,India,0.4,V Kohli,M Jansen,2,{},{}
4,1st innings,India,0.5,V Kohli,M Jansen,0,{},{}
...,...,...,...,...,...,...,...,...
246,2nd innings,South Africa,19.3,K Rabada,HH Pandya,1,{'byes': 1},{}
247,2nd innings,South Africa,19.4,KA Maharaj,HH Pandya,1,{'legbyes': 1},{}
248,2nd innings,South Africa,19.5,K Rabada,HH Pandya,1,{'wides': 1},{}
249,2nd innings,South Africa,19.6,K Rabada,HH Pandya,0,{},"{'player_out': 'K Rabada', 'fielders': ['SA Ya..."
250,2nd innings,South Africa,19.7,A Nortje,HH Pandya,1,{},{}

In [5]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 251 entries, 0 to 250
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   inning        251 non-null    object
 1   batting_team  251 non-null    object
 2   ball          251 non-null    float64
 3   batsman       251 non-null    object
 4   bowler        251 non-null    object
 5   runs          251 non-null    int64
 6   extras        251 non-null    object
 7   wicket        251 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 15.8+ KB

inning          0
batting_team    0
ball            0
batsman         0
bowler          0
runs            0
extras          0
wicket          0
dtype: int64

In [6]:
df['extras'].sample(5)
df['wicket'].sample(5)

79     {}
104    {}
32     {}
231    {}
91     {}
Name: wicket, dtype: object

In [10]:
df['extras'] = df['extras'].apply(lambda x: ast.literal_eval(x) if pd.notnull(x) and x != '{}' else {})
df['wicket'] = df['wicket'].apply(lambda x: ast.literal_eval(x) if pd.notnull(x) and x != '{}' else {})

In [6]:
# Check unique innings
print("Innings:", df['inning'].unique())

# Top players
print("Top batsmen:", df['batsman'].value_counts().head(5))
print("Top bowlers:", df['bowler'].value_counts().head(5))

# Run distribution
df['runs'].describe()

Innings: ['1st innings' '2nd innings']
Top batsmen: batsman
V Kohli      62
AR Patel     32
Q de Kock    31
H Klaasen    29
T Stubbs     21
Name: count, dtype: int64
Top bowlers: bowler
M Jansen          26
K Rabada          26
A Nortje          26
AR Patel          26
Arshdeep Singh    24
Name: count, dtype: int64

count    251.000000
mean       1.374502
std        1.638044
min        0.000000
25%        0.000000
50%        1.000000
75%        1.000000
max        6.000000
Name: runs, dtype: float64

In [7]:
df

,inning,batting_team,ball,batsman,bowler,runs,extras,wicket
0,1st innings,India,0.1,RG Sharma,M Jansen,1,{},{}
1,1st innings,India,0.2,V Kohli,M Jansen,4,{},{}
2,1st innings,India,0.3,V Kohli,M Jansen,4,{},{}
3,1st innings,India,0.4,V Kohli,M Jansen,2,{},{}
4,1st innings,India,0.5,V Kohli,M Jansen,0,{},{}
...,...,...,...,...,...,...,...,...
246,2nd innings,South Africa,19.3,K Rabada,HH Pandya,1,{'byes': 1},{}
247,2nd innings,South Africa,19.4,KA Maharaj,HH Pandya,1,{'legbyes': 1},{}
248,2nd innings,South Africa,19.5,K Rabada,HH Pandya,1,{'wides': 1},{}
249,2nd innings,South Africa,19.6,K Rabada,HH Pandya,0,{},"{'player_out': 'K Rabada', 'fielders': ['SA Ya..."
250,2nd innings,South Africa,19.7,A Nortje,HH Pandya,1,{},{}

In [8]:
print(df['extras'].iloc[0])
print(df['wicket'].iloc[0])

{}
{}